In [7]:
num = 1+1 + 2 / 5
num

2.4

In [48]:
# variable_name : variable_type = variable_value

num_integer : float = 10.1
num_float : float = 1.
num_string : str = 123

type(num_integer), type(num_float), type(num_string)

(float, float, int)

In [49]:
int(num_integer)

10

## Type of Data

#### Scalar Data Types
- int
- float
- bool
- NoneType

#### Non-Scalar Data Types
- vector
- matrix
- tensor

In [67]:
# list

list_A = [1,5,34,2 ,7,1,1,1,4]
list_A, len(list_A)

([1, 5, 34, 2, 7, 1, 1, 1, 4], 9)

In [80]:
list_A, list_A[::]

([1, 5, 34, 2, 7, 1, 1, 1, 4], [1, 5, 34, 2, 7, 1, 1, 1, 4])

In [82]:
list_A

[1, 5, 34, 2, 7, 1, 1, 1, 4]

In [85]:
list_A[0:len(list_A)-2:1], list_A[:-2]

([1, 5, 34, 2, 7, 1, 1], [1, 5, 34, 2, 7, 1, 1])

In [86]:
list_A[:-1], list_A[1:]

([1, 5, 34, 2, 7, 1, 1, 1], [5, 34, 2, 7, 1, 1, 1, 4])

In [87]:
list_A[:-1] + list_A[1:]

[1, 5, 34, 2, 7, 1, 1, 1, 5, 34, 2, 7, 1, 1, 1, 4]

## Tuple

In [75]:
coordinate : tuple = 1, 3
coordinate, 4

((1, 3), 4)

## Slices

[`start_index`:`stop_index`:`interval`]

In [71]:
list_A[21:0:-2]

[4, 1, 7, 34]

In [56]:
type(list_A[2])

int

In [90]:
import numpy as np

aa = np.array([1,2,3,1,1,1,1,7])
bb = np.array([1,-2,3,1,1,1,-1,7])

aa / bb

array([ 1., -1.,  1.,  1.,  1.,  1., -1.,  1.])

In [102]:
mat = np.array([[2,3,4],[4,5,1],[9,0,-1]])
vec = np.array([1, 5 , 7])
vec @ mat, mat @ vec

(array([85, 28,  2]), array([45, 36,  2]))

In [105]:
mat

array([[ 2,  3,  4],
       [ 4,  5,  1],
       [ 9,  0, -1]])

In [114]:
com_mat = np.array([[2,3,4j + 1],[4,5,1j],[9,0,-1]])

com_mat

array([[ 2.+0.j,  3.+0.j,  1.+4.j],
       [ 4.+0.j,  5.+0.j,  0.+1.j],
       [ 9.+0.j,  0.+0.j, -1.+0.j]])

In [120]:
(0.1j)**2

(-0.010000000000000002+0j)

In [115]:
com_mat + com_mat.T

array([[ 4.+0.j,  7.+0.j, 10.+4.j],
       [ 7.+0.j, 10.+0.j,  0.+1.j],
       [10.+4.j,  0.+1.j, -2.+0.j]])

In [116]:
com_mat.T

array([[ 2.+0.j,  4.+0.j,  9.+0.j],
       [ 3.+0.j,  5.+0.j,  0.+0.j],
       [ 1.+4.j,  0.+1.j, -1.+0.j]])

In [109]:
mat.T

array([[ 2,  4,  9],
       [ 3,  5,  0],
       [ 4,  1, -1]])

In [108]:
mat[1, :] + mat[2, :]

array([13,  5,  0])

In [104]:
mat.shape

(3, 3)

In [91]:
type(aa)

numpy.ndarray